# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
  release:
    types:
      - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  CoverageReport: ${{ github.workspace }}/coverage

defaults:
  run:
    shell: pwsh

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x

    - name: Install Coverlet for Code Coverage
      run: dotnet tool install --global coverlet.console

    - name: Run tests with code coverage
      run: |
        dotnet test BiermanTech.CriticalDog.Tests --configuration Release --collect:"XPlat Code Coverage" --results-directory ${{ env.CoverageReport }}

    - name: Convert Coverage to Cobertura Format
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:${{ env.CoverageReport }}/**/coverage.cobertura.xml -targetdir:${{ env.CoverageReport }}/html -reporttypes:Cobertura

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ${{ env.CoverageReport }}/html